### ISSUE TITLE
Generating GO function call

### ISSUE THREAD

**Issue by ManojKumarChauhan** [mxz297/dyninst#5]
Create a go binary. Create a function with arguments in go library. Instrument library function at entry point of some binary function. Using code coverage, open binary in edit mode, instrument the function and write output file. codecoverage application will crash while writing output file.

**Comment by mxz297** [comment]
@ManojKumarChauhan I pushed a new commit that will pass parameters on stack for go binaries. Your previous sample that has two parameters now works on my end. Right now, this is still only for binary rewriting.

**Comment by ManojKumarChauhan** [comment]
Will you also cover the running process case in this bug?

I have created another bug for dynamic instrumentation
https://github.com/mxz297/dyninst/issues/6

**Comment by mxz297** [comment]
@ManojKumarChauhan Yes, but that will take more time as I have not thought about dynamic instrumentation in more details. Does latest code work for you in binary rewriting cases?

**Comment by ManojKumarChauhan** [comment]
Yes it's working and there is no crash.

**Comment by mxz297** [comment]
OK. I will then start to think about how to do dynamic instrumentation
